---
- name: testing user module
  hosts: all
  become: yes 

  tasks:
  - name: Add ansible local user to the server 
    user: 
     name: ansible1 
     uid: 602 
     comment: "Ansible admin user" 
     home: /opt/ansible1/ 
     createhome: yes 
     state: present
