---
# tasks file for php
- name: install php and git
  yum: name={{item}} state=present
  with_items:
  - php
  - php-mysql
  - git

- name: copy the code from repository
  git: repo={{repository}} dest=/var/www/html/

- name: create the index.php file
  template: src=index.php.j2 dest=/var/www/html/index.php
